### ISSUE TITLE
Ubuntu 22.04 issues

### ISSUE THREAD

**Issue by Rodgers13** [mevdschee/bitlocker-tools#1] opened 2022-05-25 01:16 UTC
Hello, unfortunately I seem to have run into some troubles with Ubuntu 22.04. After using your scripts, Everything seems to set up fine but at the luks prompt It dosent seem to find/accept the key file on the usb.

I then tried following your step by step instructions https://tqdev.com/2022-luks-with-usb-unlock. At the luks screen it just loops continuously saying I've tried to many times unsuccessfully.

Is there and issue with 22.04 that you might be aware of? Could it be a hardware problem?

Thanks

**Comment by mevdschee** [comment] 2022-05-25 21:07
Hi Rodgers13, I'm sorry to hear that. I haven't tested on Ubuntu 22.04 yet, but I sure will (and update this issue). I don't expect it to be a hardware issue, as the solution is quite generic. Kind regards, Maurits

**Comment by mheppner** [comment] 2022-08-12 14:41
@Rodgers13 I had this issue too, on Debian 11. `mount` was failing for the partition containing the key file, with an error message of "device does not exist."

I found this [`unlock-root.sh`](https://github.com/hilbix/LUKS/blob/master/unlock-root.sh) script. Instead of adding a filesystem and mounting it on boot, the keyfile is written directly to the first partition. The script just uses `dd` to read in the raw disk content.

Also, a big thank you to mevdschee for this repo and the very well-written blog post, I found it to be very helpful 🥇 

---

```
# find your USB stick in /dev/disk/by-id/usb-*
export $KEY=/dev/disk/by-id/usb-THE-DEVICE-YOU-WANT-TO-USE-part1

# write the keyfile contents to the first partition
dd if=keyfile-you-created.lek of=$KEY bs=1 count=256

# use the script above, fill out $KEY and set $LEN=256
```

**Comment by mevdschee** [comment] 2022-08-12 15:33
I'll review the installation instructions and scripts for 22.04 .. just downloaded mint xfce 21 and ubuntu 22.04.1.. I'll let you know.

**Comment by mevdschee** [comment] 2022-08-14 14:18
I installed the script and it works flawless on Mint XFCE 21 (ubuntu 22.04 based). I'll try normal Ubuntu 22.04 now..

**Comment by mevdschee** [comment] 2022-08-14 14:38
I've checked Ubuntu 22.04 (desktop) and it works without modification as well.

**Comment by mevdschee** [comment] 2022-08-14 14:48
Debian 11 might work out of the box..

![image](https://user-images.githubusercontent.com/1288217/184542334-31d22b48-adb9-4db3-ade4-6642c786e0a7.png)

**Comment by mevdschee** [comment] 2022-08-14 20:17
>Is there and issue with 22.04 that you might be aware of? Could it be a hardware problem?

@Rodgers13 I've tested with a clean install (in a vm) and can't reproduce the problem you have, can you help me reproduce?

Kind regards, Maurits

**Comment by palemium** [comment] 2022-09-18 21:57
@mevdschee Hi, I am not sure if It's related but I was following https://tqdev.com/2022-luks-with-usb-unlock to set it up on debian 11. And I had to add `usb_storage` to `/etc/initramfs-tools/modules` to fix the issue with loading. I use non gui version - maybe that was the reason it did not work out of box. Thanks for the article!

**Comment by mevdschee** [comment] 2022-09-19 05:57
@palemium, thank you, I updated the article, did you see #2?

**Comment by palemium** [comment] 2022-09-21 16:18
@mevdschee yes, I saw it - I thought open Ubuntu issue can be related since it is based on Debian. The article works for me (Debian 11, no GUI) when this single line in modules file was added. 

BTW, I saw similar continuous loop when I was trying to debug the script and added additional echo statements. Probably, these symptoms mean some copy-paste error in the script.

**Comment by mevdschee** [comment] 2022-09-21 17:24
> and added additional echo statements

Yes, you can't add echo statements, but that is different issue (due to input/output redirection).

>Probably, these symptoms mean some copy-paste error in the script.

Maybe indeed that is what went wrong for @Rodgers13, thank you for suggesting this.

**Comment by mevdschee** [comment] 2022-09-21 17:31
Closing this issue as the instructions seem to work for both Ubuntu 22.04 and Debian 11

**Closed as completed by mevdschee** 2022-09-21 17:31 UTC
Labels: help wanted
